name: teslo_shop
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.4 <3.0.0'

dependencies:
  dio: ^5.6.0
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.1.0
  flutter_native_splash: ^2.4.1
  flutter_riverpod: ^2.5.1
  flutter_staggered_grid_view: ^0.7.0
  formz: ^0.7.0
  go_router: ^14.2.3
  google_fonts: ^6.2.1
  image_picker: ^1.1.2
  img_picker_platform_interface: ^3.0.0
  shared_preferences: ^2.3.2

dev_dependencies:
  change_app_package_name: ^1.3.0
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/app-icon-2.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/icon/app-icon-1.jpeg"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "assets/icon/app-icon-2.png"
    icon_size: 48 # min:48, max:256, default: 48

flutter_native_splash:
  color: "#F3F3F3"
  image_web: assets/loaders/box-1805.gif

flutter:
  uses-material-design: true

  assets:
    - assets/loaders/
    - assets/images/
    - assets/icon/
    - google_fonts/montserrat_alternates/
    - .env
